name: Build LaTeX document
run-name: ${{ GITHUB.ACTOR }} is compiling a Latex Document 🚀
on:  
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-latex.yml"
      - "content/**"
      - "main.tex"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Search for directory
        run: ls -l
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file as Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            main.pdf
      - name: Upload PDF file as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Latex Dokumentation
          path: main.pdf

